version: '3.3'

services:

  app:
    build:
      args:
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: fight-simulator:1.0
    container_name: fight-simulator
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
